name: CI - Validation Extension TYPO3

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, intl, json

      - name: Validation du fichier composer.json
        run: composer validate --strict

      - name: Vérification de la syntaxe PHP (Lint)
        run: |
          find Classes/ Configuration/ -name "*.php" -print0 | xargs -0 -n1 -P4 php -l
