name: Release TYPO3 Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Création de l'archive ZIP d'extension
        run: |
          git archive --format=zip --prefix=site_commune_rgaa/ HEAD -o site_commune_rgaa_${{ github.ref_name }}.zip

      - name: Publier sur GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: site_commune_rgaa_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
